### ISSUE TITLE
Warning Generating documentation with doxygen

### ISSUE THREAD

**Issue by davidfdzp** [drmpeg/gr-dvbs2rx38#1]
make

[ 35%] Generating documentation with doxygen

warning: tag INPUT: input source `/mnt/c/Users/David\ Fernandez\ Pina/gr-dvbs2rx38' does not exist

warning: tag INPUT: input source `/mnt/c/Users/David\ Fernandez\ Pina/gr-dvbs2rx38/build' does not exist

warning: source /mnt/c/Users/David\ Fernandez\ Pina/gr-dvbs2rx38 is not a readable file or directory... skipping.

warning: source /mnt/c/Users/David\ Fernandez\ Pina/gr-dvbs2rx38/build is not a readable file or directory... skipping.

**Comment by drmpeg** [comment]
Maybe Doxygen doesn't like directory names with spaces? A workaround would be to disable Doxygen by adding -DENABLE_DOXYGEN=OFF to the cmake command line.

**Comment by davidfdzp** [comment]
Confirmed: Doxygen doesn't like directory names with spaces, something I was sure was going to cause me troubles when I saw the IT guys made my user name with spaces. Fortunately, a soft-link did the trick.
